#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v10
# autospec commit: 6fa3d52db448
#
Name     : plog
Version  : 1.1.10
Release  : 1
URL      : https://github.com/SergiusTheBest/plog/archive/1.1.10/plog-1.1.10.tar.gz
Source0  : https://github.com/SergiusTheBest/plog/archive/1.1.10/plog-1.1.10.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: plog-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Plog - portable, simple and extensible C++ logging library
Pretty powerful logging library in about 1000 lines of code [![CI](https://github.com/SergiusTheBest/plog/actions/workflows/ci.yml/badge.svg)](https://github.com/SergiusTheBest/plog/actions/workflows/ci.yml) [![Build status](https://ci.appveyor.com/api/projects/status/rna5gwhqjb13wovr/branch/master?svg=true)](https://ci.appveyor.com/project/SergiusTheBest/plog/branch/master) [![CircleCI](https://circleci.com/gh/SergiusTheBest/plog.svg?style=svg)](https://circleci.com/gh/SergiusTheBest/plog) [![Build Status](https://api.cirrus-ci.com/github/SergiusTheBest/plog.svg)](https://cirrus-ci.com/github/SergiusTheBest/plog)

%package dev
Summary: dev components for the plog package.
Group: Development
Provides: plog-devel = %{version}-%{release}
Requires: plog = %{version}-%{release}

%description dev
dev components for the plog package.


%package doc
Summary: doc components for the plog package.
Group: Documentation

%description doc
doc components for the plog package.


%package license
Summary: license components for the plog package.
Group: Default

%description license
license components for the plog package.


%prep
%setup -q -n plog-1.1.10
cd %{_builddir}/plog-1.1.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1716938157
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1716938157
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plog
cp %{_builddir}/plog-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/plog/702ff74c289fef8d7a1926a5be9be731800c90ff || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/plog/Appenders/AndroidAppender.h
/usr/include/plog/Appenders/ArduinoAppender.h
/usr/include/plog/Appenders/ColorConsoleAppender.h
/usr/include/plog/Appenders/ConsoleAppender.h
/usr/include/plog/Appenders/DebugOutputAppender.h
/usr/include/plog/Appenders/DynamicAppender.h
/usr/include/plog/Appenders/EventLogAppender.h
/usr/include/plog/Appenders/IAppender.h
/usr/include/plog/Appenders/RollingFileAppender.h
/usr/include/plog/Converters/NativeEOLConverter.h
/usr/include/plog/Converters/UTF8Converter.h
/usr/include/plog/Formatters/CsvFormatter.h
/usr/include/plog/Formatters/FuncMessageFormatter.h
/usr/include/plog/Formatters/MessageOnlyFormatter.h
/usr/include/plog/Formatters/TxtFormatter.h
/usr/include/plog/Helpers/AscDump.h
/usr/include/plog/Helpers/HexDump.h
/usr/include/plog/Helpers/PrintVar.h
/usr/include/plog/Init.h
/usr/include/plog/Initializers/ConsoleInitializer.h
/usr/include/plog/Initializers/RollingFileInitializer.h
/usr/include/plog/Log.h
/usr/include/plog/Logger.h
/usr/include/plog/Record.h
/usr/include/plog/Severity.h
/usr/include/plog/Util.h
/usr/include/plog/WinApi.h
/usr/lib64/cmake/plog/plogConfig.cmake
/usr/lib64/cmake/plog/plogConfigVersion.cmake

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/plog/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plog/702ff74c289fef8d7a1926a5be9be731800c90ff
